name = "{{{PKG}}}"
uuid = "{{{UUID}}}"
authors = {{{AUTHORS}}}
version = "0.0.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
DocStringExtensions = "0.9.3"
julia = "1.10"
